
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-11
owner: ucsb-cs156-f25
repo_name: team01-f25-11
pull_requests: [{"author":{"id":"U_kgDOCNoLqQ","is_bot":false,"login":"SagnikBiswasUCSB","name":""},"headRefName":"sagnikbiswas-getrequest","number":47,"title":"Sagnikbiswas getrequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-11/pull/47"},{"author":{"id":"U_kgDOCNoLqQ","is_bot":false,"login":"SagnikBiswasUCSB","name":""},"headRefName":"sagnikbiswas-putrequest","number":46,"title":"Sagnikbiswas putrequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-11/pull/46"},{"author":{"id":"U_kgDOCNoLqQ","is_bot":false,"login":"SagnikBiswasUCSB","name":""},"headRefName":"sagnikbiswas-recommendationcontroller","number":45,"title":"Sagnikbiswas recommendationcontroller","url":"https://github.com/ucsb-cs156-f25/team01-f25-11/pull/45"},{"author":{"id":"U_kgDOCNoLqQ","is_bot":false,"login":"SagnikBiswasUCSB","name":""},"headRefName":"sagnikbiswas-RecommendationRequest-create-db","number":44,"title":"finished recommendation db","url":"https://github.com/ucsb-cs156-f25/team01-f25-11/pull/44"}]
